---
- name: install jdk
  aur:
    name: jdk

- name: find latest java version
  shell: java -version |& awk -F'"' '{print $2}' |& cut -d. -f1
  register: java_version_str

- name: save java version bounds
  set_fact:
    max_jdk: "{{ java_version_str.stdout_lines[0] }}"
    min_jdk: "{{ min_jdk | default(java_version_str.stdout_lines[0]) }}"

- name: install older jdks
  aur:
    name: "jdk{{ item }}"
  loop: "{{ range(min_jdk | int, max_jdk | int) | list }}"

- name: create oracle config dir
  file:
    path: /etc/oracle/java/
    state: directory
  become: true

- name: disable oracle usage tracking
  copy:
    src: usagetracker.properties
    dest: /etc/oracle/java/
  become: true
