---
- name: create ramdisk mount
  mount:
    path: /mnt/ramdisk
    state: mounted
    src: tmpfs
    fstype: tmpfs
  become: yes

- name: create .local dir
  file:
    path: "{{ ansible_env.HOME }}/.local"
    state: directory

- name: install ramdisk backup script
  copy:
    src: ramdisk-backup.sh
    dest: "{{ ansible_env.HOME }}/.local/"

- name: install ramdisk backup service
  template:
    src: ramdisk-backup.service
    dest: "/etc/systemd/system/"
  become: yes

- name: run backup service
  systemd:
    name: ramdisk-backup
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
